baseURL = "https://christianmahnke.de/"
languageCode = "de"
title = "Christian Mahnke"
languagecode = "de"
defaultcontentlanguage = "de"
copyright = "Christian Mahnke"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
theme = ["projektemacher-base", "hugo-video"]

[languages]
    [languages.de]
        languagename = "Deutsch"

        [languages.de.menu]

            [[languages.de.menu.main]]
                name = "Schwerpunkte"
                URL = "/"
                weight = 2

            [[languages.de.menu.main]]
                name = "Sammlungen"
                URL = "/collections"
                weight = 3

            [[languages.de.menu.main]]
                name = "Blog"
                URL = "/post"
                weight = 4

            [[languages.de.menu.main]]
                name = "Über"
                weight = 5
                url = "about"

    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
                name = "Focuses"
                URL = "/"
                weight = 2

            [[languages.en.menu.main]]
                name = "Collections"
                URL = "/collections"
                weight = 3

            [[languages.en.menu.main]]
                name = "Blog"
                weight = 4
                url = "en/post"

            [[languages.en.menu.main]]
                name = "About"
                weight = 5
                url = "en/about"

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe= true

    [markup.goldmark.extensions]
        typographer = true
        attribute = true

    [markup.goldmark.parser]
        autoHeadingID = true
        autoHeadingIDType = "github"

[imaging]
    quality = 95

[mediaTypes]
  [mediaTypes."application/geo+json"]
    suffixes = ["geojson", "gjson"]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.geojson]
    mediaType = "application/geo+json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true

  [outputFormats.iiif]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

[privacy]
  [privacy.instagram]
    disable = false
    simple = false

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

    [[module.mounts]]
        source = "node_modules/elevator.js/demo/music/"
        target = "static/sounds"
