baseURL = "https://christianmahnke.de/"
languageCode = "de"
title = "Christian Mahnke"
languagecode = "de"
defaultcontentlanguage = "de"
copyright = "Christian Mahnke"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
theme = ["projektemacher-base", "hugo-video"]
enableGitInfo = true
preserveTaxonomyNames = true
enableRobotsTXT = true
timeout = "120s"

[languages]
    [languages.de]
        languagename = "Deutsch"

        [languages.de.menu]

            [[languages.de.menu.main]]
                name = "Schwerpunkte"
                URL = "/"
                weight = 2

            [[languages.de.menu.main]]
                name = "Sammlungen"
                URL = "/collections"
                weight = 3

            [[languages.de.menu.main]]
                name = "Blog"
                URL = "/post"
                weight = 4

            [[languages.de.menu.main]]
                name = "Links"
                URL = "/links"
                weight = 5

            [[languages.de.menu.main]]
                name = "Über"
                weight = 6
                url = "about"

            [[languages.de.menu.main]]
                name = '<form action="/search/" method="get" class="search-form"><input name="q" type="text" placeholder="Suche" class="search-input" id="menu-search-input"><button type="submit" class="search-button" id="menu-search-button"><i class="search-icon"></i></button></form>'
                weight = 7
                url = "search"

                [[languages.de.menu.main.params]]
                    html = true
                    draft = true

    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
                name = "Focuses"
                URL = "/"
                weight = 2

            [[languages.en.menu.main]]
                name = "Collections"
                URL = "/collections"
                weight = 3

            [[languages.en.menu.main]]
                name = "Blog"
                weight = 4
                url = "en/post"

            [[languages.en.menu.main]]
                name = "Links"
                weight = 5
                url = "en/links"

            [[languages.en.menu.main]]
                name = "About"
                weight = 6
                url = "en/about"

            [[languages.en.menu.main]]
                name = '<form action="/en/search/" method="get" class="search-form"><input name="q" type="text" placeholder="Suche" class="search-input" id="menu-search-input"><button type="submit" class="search-button" id="menu-search-button"><i class="search-icon"></i></button></form>'
                weight = 7
                url = "search"

                [[languages.en.menu.main.params]]
                    html = true
                    draft = true

[markup]
    defaultMarkdownHandler = 'goldmark'

[markup.goldmark]
    duplicateResourceFiles = true

    [markup.goldmark.renderer]
        unsafe= true

    [markup.goldmark.extensions]
        attribute = true
        strikethrough = true

    [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.insert]
            enable = true
        [markup.goldmark.extensions.extras.mark]
            enable = true
        [markup.goldmark.extensions.extras.subscript]
            enable = true
        [markup.goldmark.extensions.extras.superscript]
            enable = true

    [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'

    [markup.goldmark.parser]
        autoHeadingID = true
        autoHeadingIDType = "github"

        [markup.goldmark.parser.attribute]
            block = true

[markup.highlight]
  noClasses = false

[imaging]
    quality = 95

[mediaTypes]
  [mediaTypes."application/geo+json"]
    suffixes = ["geojson", "gjson"]
  [mediaTypes."application/ld+json"]
    suffixes = ["json", "jsonld"]
  [mediaTypes."application/activity+json"]
    suffixes = ["json"]
  [mediaTypes."image/jxl"]
    suffixes = ["jxl"]
  [mediaTypes."text/bibtex"]
    suffixes = ["bib"]

[outputFormats]
  [outputFormats.geojson]
    mediaType = "application/geo+json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true

  [outputFormats.iiif]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

  [outputFormats.iiif-manifest]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

  [outputFormats.iiif-collection]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "collection"
    notAlternative = true

  [outputFormats.activity-pub-actor]
    mediaType = "application/activity+json"
    isPlainText = true
    isHTML = false
    baseName = "actor"
    notAlternative = true

  [outputFormats.activity-pub-outbox]
    mediaType = "application/activity+json"
    isPlainText = true
    isHTML = false
    baseName = "outbox"
    notAlternative = true

  [outputFormats.print]
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
    baseName = "print"
    notAlternative = true
    permalinkable = true

  [outputFormats.bibtex]
    mediaType = "text/bibtex"
    baseName = "citation"
    isHTML = false

[outputs]
#  page = ['html', 'print']

[privacy]
  [privacy.instagram]
    disable = false
    simple = false

[sitemap]
  changeFreq = 'weekly'

[module]
  [module.hugoVersion]
    extended = true
    min = '0.146.3'

  [[module.mounts]]
      source = "assets/scss"
      target = "assets/scss"

  [[module.mounts]]
      source = "static"
      target = "static"

  [[module.mounts]]
      source = "assets/js"
      target = "assets/js"

  [[module.mounts]]
      source = "assets/ts"
      target = "assets/ts"

  [[module.mounts]]
      source = "node_modules/elevator.js/demo/music/"
      target = "static/sounds"

  [[module.mounts]]
      source = "node_modules/photoswipe/dist"
      target = "assets/css/photoswipe"

  [[module.mounts]]
      source = "node_modules/@annotorious/openseadragon/dist"
      target = "assets/css/openseadragon"

  [[module.mounts]]
      source = "node_modules/@pagefind/modular-ui/css/"
      target = "assets/scss/pagefind"

  [[module.mounts]]
      source = "node_modules/@pagefind/default-ui"
      target = "assets/js/pagefind"

  [[module.mounts]]
      source = "static/images"
      target = "static/images"

  [[module.mounts]]
      source = "node_modules/openseadragon/build/openseadragon/images"
      target = "static/images"

[build]
  writeStats = true

[segments]
  [segments.manifests]
    [[segments.manifests.includes]]
      output = 'iiif-manifest'

[security]
  [security.http]
    mediaTypes = ['^application/json$', '^application/json;\s?charset=[uU][tT][fF]-8$', '^application/sparql-results\+json;\s?charset=[uU][tT][fF]-8$']
