name: github pages

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 23 1 * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Setup Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 10.22.0

      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.9

      - name: Install required dependencies
        run: |
          ./themes/projektemacher-base/scripts/github/setup-dependencies.sh
          ./themes/projektemacher-base/scripts/github/python-dependencies.sh
          ./themes/projektemacher-base/scripts/github/setup-inkscape.sh

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: '0.84.4'
          extended: true

      - name: Generate Files
        run: |
          ./scripts/setup.sh

      - name: Build Hugo site
        run: hugo --i18n-warnings

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
